### ISSUE TITLE
某些安卓机型点击输入框后出现键盘升起马上收回，无法输入的问题

### ISSUE THREAD

**Issue by geraldlrh** [sdc-fe/Framework7-Plus#24]
只要点击页面底部的input或者textarea(键盘升起后能覆盖到的)，就会出现这种情况。
初步追查发现是Framework7的样式的问题，页面内容都是在.page-content里面内滚动导致的：
```css
.page {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
}
.page-content {
  overflow: auto;
  height: 100%;
  position: relative;
}
```
试了下Framework7-plus，发现也没有解决这个问题。
问题机型包括：红米Note(4.2) 、oppo轻装版(4.3)、 华为荣耀（4.2）
